name = "akpro2026web"
compatibility_date = "2025-02-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NEXT_PUBLIC_USE_TURSO = "true"


[[kv_namespaces]]
binding = "PUBLIC_DATA"
id = "768e1916351445518db68fdf03327be9"